### PR TITLE
Support for compiled queries fixes #25

### LINKED ISSUE #25: Support for compiled queries
Nice project! Is there a way to support Compiled queries?

I was trying something like:
````scala
implicit class BlockingAppliedCompiledFunction[PU, R <: Rep[_], RU]
    (f: AppliedCompiledFunction[PU, R, RU]) {

  def firstOption(implicit s: JdbcBackend#Session): Option[R] = {
    val invoker = new QueryInvoker[R](f.compiledQuery)
    invoker.firstOption
  }

}
````

But the type of `R` is not what I expected. Any clue how to implement this?

### PR DESCRIPTION
**Pull request by jtjeferreira**

### CODE REVIEW

**Comment by takezoe** [comment]
@vanDonselaar Could you test this branch?

**Comment by vanDonselaar** [comment]
Tested with a code base having ~90 non-compiled queries and found no regressions. Rewrote 3 queries to a compiled query (a simple one, one with explicit joins, and one with monadic i.e. for-style joins, all parameterized). Seems to work perfectly. Great work @jtjeferreira. And thanks @takezoe for maintaining this project. Ship it! :tada:

**Comment by takezoe** [comment]
@vanDonselaar Thanks for testing! I will merge this request and release a new version.

@jtjeferreira Really great work! Thank you!

**Comment by jtjeferreira** [comment]
Just a side note regarding using blocking-slick to migrate codebases from slick2 to slick3:

In my project we had an issue in production because we were using `Database.forDataSource(DB.getDataSource())` for every request to get a `Database` instance. In slick2 this worked fine, while in slick3 this is always creating new Database objects, each with his own threadpool

more details here: https://github.com/knoldus/play-reactive-slick/issues/1

**Pull request merged**
